# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDB' do
  use_frameworks!
  pod 'Alamofire' , '4.8.2'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Kingfisher', '~> 6.0'
  pod 'CleanyModal'
  # Pods for TMDB

  target 'TMDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDBUITests' do
    # Pods for testing
  end

end
